/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#570000',
        'primary-container': '#800000',
        'on-primary': '#ffffff',
        'on-primary-container': '#ff8371',
        'primary-fixed': '#ffdad4',
        'primary-fixed-dim': '#ffb4a8',
        'secondary': '#565e77',
        'secondary-container': '#d7dffd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5a627b',
        'secondary-fixed': '#dae2ff',
        'secondary-fixed-dim': '#bec6e3',
        'tertiary': '#332500',
        'tertiary-fixed': '#ffdf96',
        'tertiary-fixed-dim': '#e7c268',
        'on-tertiary-container': '#c6a34d',
        'surface': '#fbf9f5',
        'surface-bright': '#fbf9f5',
        'surface-dim': '#dbdad6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'surface-variant': '#e4e2de',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#5a413d',
        'outline': '#8e706c',
        'outline-variant': '#e2bfb9',
        'background': '#fbf9f5',
        'on-background': '#1b1c1a',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'border': '#e2bfb9',
        'ring': '#570000',
      },
      fontFamily: {
        montserrat: ['Montserrat', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        caveat: ['Caveat', 'cursive'],
        headline: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        note: ['Caveat', 'cursive'],
      },
      spacing: {
        gutter: '24px',
        'container-max': '1280px',
      },
      boxShadow: {
        'polaroid': '0 4px 6px rgba(0,0,0,0.08), 0 1px 3px rgba(0,0,0,0.06), 0 10px 20px -5px rgba(0,0,0,0.1)',
        'polaroid-hover': '0 20px 25px -5px rgba(0,0,0,0.15), 0 10px 10px -5px rgba(0,0,0,0.08)',
        'sticky': '2px 4px 10px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)',
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.07)',
      },
      animation: {
        'float-slow': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 7s ease-in-out 2s infinite',
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-15px) rotate(4deg)' },
        },
      },
    },
  },
  plugins: [],
};
